<?php

/**
 * BaseLeavingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $kind_leave
 * @property date $getting_started
 * @property date $end_work
 * @property string $number_vacation_days
 * @property date $commencement
 * @property date $end_leave
 * @property string $base_release
 * @property Doctrine_Collection $LeavingTable
 * 
 * @method string              getKindLeave()            Returns the current record's "kind_leave" value
 * @method date                getGettingStarted()       Returns the current record's "getting_started" value
 * @method date                getEndWork()              Returns the current record's "end_work" value
 * @method string              getNumberVacationDays()   Returns the current record's "number_vacation_days" value
 * @method date                getCommencement()         Returns the current record's "commencement" value
 * @method date                getEndLeave()             Returns the current record's "end_leave" value
 * @method string              getBaseRelease()          Returns the current record's "base_release" value
 * @method Doctrine_Collection getLeavingTable()         Returns the current record's "LeavingTable" collection
 * @method LeavingTable        setKindLeave()            Sets the current record's "kind_leave" value
 * @method LeavingTable        setGettingStarted()       Sets the current record's "getting_started" value
 * @method LeavingTable        setEndWork()              Sets the current record's "end_work" value
 * @method LeavingTable        setNumberVacationDays()   Sets the current record's "number_vacation_days" value
 * @method LeavingTable        setCommencement()         Sets the current record's "commencement" value
 * @method LeavingTable        setEndLeave()             Sets the current record's "end_leave" value
 * @method LeavingTable        setBaseRelease()          Sets the current record's "base_release" value
 * @method LeavingTable        setLeavingTable()         Sets the current record's "LeavingTable" collection
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLeavingTable extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('leaving_table');
        $this->hasColumn('kind_leave', 'string', 80, array(
             'type' => 'string',
             'length' => 80,
             ));
        $this->hasColumn('getting_started', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('end_work', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('number_vacation_days', 'string', 2, array(
             'type' => 'string',
             'length' => 2,
             ));
        $this->hasColumn('commencement', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('end_leave', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('base_release', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('JobeetJob as LeavingTable', array(
             'local' => 'id',
             'foreign' => 'leaving_table_id'));
    }
}