<?php

/**
 * BasePassport
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $passport_number
 * @property string $issuance_passports
 * @property date $date_issue_passport
 * @property string $code_division
 * @property Doctrine_Collection $Passport
 * 
 * @method string              getPassportNumber()      Returns the current record's "passport_number" value
 * @method string              getIssuancePassports()   Returns the current record's "issuance_passports" value
 * @method date                getDateIssuePassport()   Returns the current record's "date_issue_passport" value
 * @method string              getCodeDivision()        Returns the current record's "code_division" value
 * @method Doctrine_Collection getPassport()            Returns the current record's "Passport" collection
 * @method Passport            setPassportNumber()      Sets the current record's "passport_number" value
 * @method Passport            setIssuancePassports()   Sets the current record's "issuance_passports" value
 * @method Passport            setDateIssuePassport()   Sets the current record's "date_issue_passport" value
 * @method Passport            setCodeDivision()        Sets the current record's "code_division" value
 * @method Passport            setPassport()            Sets the current record's "Passport" collection
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePassport extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('passport');
        $this->hasColumn('passport_number', 'string', 11, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 11,
             ));
        $this->hasColumn('issuance_passports', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('date_issue_passport', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('code_division', 'string', 7, array(
             'type' => 'string',
             'length' => 7,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('JobeetJob as Passport', array(
             'local' => 'id',
             'foreign' => 'passport_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}