<?php

/**
 * BaseProfession
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $main_profession
 * @property string $other_profession
 * @property string $total_length
 * @property string $continuous_service
 * @property string $last_job
 * @property date $termination_date
 * @property Doctrine_Collection $Profession
 * 
 * @method string              getMainProfession()     Returns the current record's "main_profession" value
 * @method string              getOtherProfession()    Returns the current record's "other_profession" value
 * @method string              getTotalLength()        Returns the current record's "total_length" value
 * @method string              getContinuousService()  Returns the current record's "continuous_service" value
 * @method string              getLastJob()            Returns the current record's "last_job" value
 * @method date                getTerminationDate()    Returns the current record's "termination_date" value
 * @method Doctrine_Collection getProfession()         Returns the current record's "Profession" collection
 * @method Profession          setMainProfession()     Sets the current record's "main_profession" value
 * @method Profession          setOtherProfession()    Sets the current record's "other_profession" value
 * @method Profession          setTotalLength()        Sets the current record's "total_length" value
 * @method Profession          setContinuousService()  Sets the current record's "continuous_service" value
 * @method Profession          setLastJob()            Sets the current record's "last_job" value
 * @method Profession          setTerminationDate()    Sets the current record's "termination_date" value
 * @method Profession          setProfession()         Sets the current record's "Profession" collection
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfession extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profession');
        $this->hasColumn('main_profession', 'string', 40, array(
             'type' => 'string',
             'length' => 40,
             ));
        $this->hasColumn('other_profession', 'string', 40, array(
             'type' => 'string',
             'length' => 40,
             ));
        $this->hasColumn('total_length', 'string', 2, array(
             'type' => 'string',
             'length' => 2,
             ));
        $this->hasColumn('continuous_service', 'string', 2, array(
             'type' => 'string',
             'length' => 2,
             ));
        $this->hasColumn('last_job', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('termination_date', 'date', null, array(
             'type' => 'date',
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('JobeetJob as Profession', array(
             'local' => 'id',
             'foreign' => 'profession_id'));
    }
}