<?php

/**
 * BaseEducation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Jobeet
 * 
 * @method string              getName()   Returns the current record's "name" value
 * @method Doctrine_Collection getJobeet() Returns the current record's "Jobeet" collection
 * @method Education           setName()   Sets the current record's "name" value
 * @method Education           setJobeet() Sets the current record's "Jobeet" collection
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEducation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('education');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('JobeetJob as Jobeet', array(
             'local' => 'id',
             'foreign' => 'education_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}