passport:
  class: sfDoctrineRouteCollection
  options:
    model:                Passport
    module:               passport
    prefix_path:          /passport
    column:               id
    with_wildcard_routes: true

status:
  class: sfDoctrineRouteCollection
  options:
    model:                Status
    module:               status
    prefix_path:          /status
    column:               id
    with_wildcard_routes: true

city:
  class: sfDoctrineRouteCollection
  options:
    model:                City
    module:               city
    prefix_path:          /city
    column:               id
    with_wildcard_routes: true

education:
  class: sfDoctrineRouteCollection
  options:
    model:                Education
    module:               education
    prefix_path:          /education
    column:               id
    with_wildcard_routes: true

jobeet_category:
  class: sfDoctrineRouteCollection
  options:
    model:                JobeetCategory
    module:               category
    prefix_path:          /category
    column:               id
    with_wildcard_routes: true

jobeet_job:
  class: sfDoctrineRouteCollection
  options:
    model:                JobeetJob
    module:               job
    prefix_path:          /job
    column:               id
    with_wildcard_routes: true

show:
  class: sfDoctrineRouteCollection
  options:
    model:                JobeetJob
    prefix_path:          /show
  url: show
  param:
    module: job
    action: show

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: job, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
