<?php
// auto-generated by sfSecurityConfigHandler
<<<<<<< HEAD
// date: 2011/03/30 17:19:58
=======
// date: 2011/03/30 20:32:03
>>>>>>> ec27b1c97778c436fba45a676ab851b3ad70cb2c
$this->security = array (
  'all' => 
  array (
    'is_secure' => false,
  ),
);
