<?php
// auto-generated by sfDefineEnvironmentConfigHandler
<<<<<<< HEAD
// date: 2011/03/30 17:19:58
=======
// date: 2011/03/30 20:32:03
>>>>>>> ec27b1c97778c436fba45a676ab851b3ad70cb2c
sfConfig::add(array(
  'mod_default_enabled' => true,
  'mod_default_view_class' => 'sfPHP',
));
