<?php

/**
 * EducationalInstitutionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EducationalInstitutionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EducationalInstitutionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EducationalInstitution');
    }
}