<?php

/**
 * EducationalInstitution
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EducationalInstitution extends BaseEducationalInstitution
{
    public function save(Doctrine_Connection $conn = null)
{
  return parent::save($conn);

}
}
