<?php

/**
 * EducationalInstitutionExtraTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EducationalInstitutionExtraTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EducationalInstitutionExtraTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EducationalInstitutionExtra');
    }
}