<?php

/**
 * ForeignLanguageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ForeignLanguageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ForeignLanguageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ForeignLanguage');
    }
}