<?php

/**
 * JobeetJobTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobeetJobTable extends Doctrine_Table
{

    static public $typestype = array(
    'M'   => 'М',
    'Ж' => 'Ж'
        );

     static public $typestypework = array(
    'Основная'            => 'Основная',
    'По совместительству' => 'По совместительству'
        );

     static public $foreignlanguages = array(
    'Читает и переводит со словарем'     => 'Читает и переводит со словарем',
    'Читает и может объясняться'         => 'Читает и может объясняться',
     'Владеет свободно'                  => 'Владеет свободно'
        );

     static public $naturework = array(
    'Постоянная' => 'Постоянная',
    'Временная'  => 'Временная'
        );


      public function getNatureWork()
      {
        return self::$naturework;
      }

     public function getForeignLanguages()
      {
        return self::$foreignlanguages;
      }

     public function getTypesType()
      {
        return self::$typestype;
      }

     public function getTypesTypeWork()
      {
        return self::$typestypework;
      }


  // ...
}