<?php

/**
 * JobeetJobTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobeetJobTable extends Doctrine_Table
{

    static public $types = array(
    'male' => 'М',
    'female' => 'Ж'
        );



   public function getTypes()
  {
    return self::$types;
  }


  // ...
}