<?php

/**
 * LeavingTableTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LeavingTableTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LeavingTableTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LeavingTable');
    }
}