<?php

/**
 * MilitaryRecordsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MilitaryRecordsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MilitaryRecordsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MilitaryRecords');
    }
}