<?php

/**
 * PassportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PassportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PassportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Passport');
    }
}