<?php

/**
 * ProfessionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfessionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfessionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Profession');
    }
}