<?php
// auto-generated by sfGeneratorConfigHandler
<<<<<<< HEAD
// date: 2011/03/30 17:19:55
=======
// date: 2011/03/30 20:42:38
>>>>>>> ec27b1c97778c436fba45a676ab851b3ad70cb2c
require_once(sfConfig::get('sf_module_cache_dir').'/autoJob/actions/actions.class.php');
