<?php
// auto-generated by sfDefineEnvironmentConfigHandler
<<<<<<< HEAD
// date: 2011/03/30 17:19:55
=======
// date: 2011/03/30 20:42:38
>>>>>>> ec27b1c97778c436fba45a676ab851b3ad70cb2c
sfConfig::add(array(
  'mod_job_enabled' => true,
  'mod_job_view_class' => 'sfPHP',
));
