<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/03/06 14:04:28
$this->security = array (
  'index' => 
  array (
    'is_secure' => true,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
