<?php
// auto-generated by sfSecurityConfigHandler
<<<<<<< HEAD
// date: 2011/03/30 17:29:38
=======
// date: 2011/03/26 19:40:40
>>>>>>> ec27b1c97778c436fba45a676ab851b3ad70cb2c
$this->security = array (
  'index' => 
  array (
    'credentials' => 
    array (
      0 => 'ADMIN',
    ),
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
