<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/04/03 16:41:40
$this->security = array (
  'index' => 
  array (
    'credentials' => 
    array (
      0 => 'ADMIN',
    ),
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
