<?php
// auto-generated by sfSecurityConfigHandler
<<<<<<< HEAD
// date: 2011/03/30 17:19:55
=======
// date: 2011/03/30 20:43:40
>>>>>>> ec27b1c97778c436fba45a676ab851b3ad70cb2c
$this->security = array (
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'signout' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
