<?php
// auto-generated by sfDefineEnvironmentConfigHandler
<<<<<<< HEAD
// date: 2011/03/30 17:29:40
=======
// date: 2011/03/26 20:14:47
>>>>>>> ec27b1c97778c436fba45a676ab851b3ad70cb2c
sfConfig::add(array(
  'mod_sfguarduser_enabled' => true,
  'mod_sfguarduser_view_class' => 'sfPHP',
));
