<?php
// auto-generated by sfGeneratorConfigHandler
<<<<<<< HEAD
// date: 2011/03/30 17:29:40
=======
// date: 2011/03/26 20:14:47
>>>>>>> ec27b1c97778c436fba45a676ab851b3ad70cb2c
require_once(sfConfig::get('sf_module_cache_dir').'/autoSfGuardUser/actions/actions.class.php');
