<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/02/27 22:28:46
$this->security = array (
  'index' => 
  array (
    'is_secure' => true,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
