<?php
// auto-generated by sfDefineEnvironmentConfigHandler
<<<<<<< HEAD
// date: 2011/03/30 17:29:38
=======
// date: 2011/03/26 19:40:40
>>>>>>> ec27b1c97778c436fba45a676ab851b3ad70cb2c
sfConfig::add(array(
  'mod_city_enabled' => true,
  'mod_city_view_class' => 'sfPHP',
));
