generator:
  class: sfDoctrineGenerator
  param:
    model_class:           City
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          city
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [name]
        title: Города
        sort: [name]
      filter:
        display: [name]
      form:    ~
      edit:
        title: Редактировать город
      new:
        title: Добавить город

