generator:
  class: sfDoctrineGenerator
  param:
    model_class:           JobeetJob
    theme:                 admin
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          jobeet_job
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
         display: [tab_id, =jobeet_category, first_name, last_name, data_id, education]
         title: Сотрудники
      filter:
          display: [tab_id, last_name, first_name]
      form:
        display:
         Начальные сведения: [ sf_guard_user_id, tab_id, number_insurace, pension_sertificate, nature_work, type_work, category_id, status_id, price ]
         Общие сведения: [ last_name, first_name, three_name, type, data_birth, phone, mobile_phone, city_id, adress, email, logo ]
         Паспорт: [ Passport ]
         Знание иностранных языков: [ ForeignLanguage ]
         Образование: [ EducationalInstitution ]
         Послевузовое профессиональное образование: [ EducationalInstitutionExtra ]
         Профессия: [ Profession ]
         Семейное положение: [ Family ]
         Воинский учет: [ group_accounting, category_accounting, composition, military_rank, military_discount_specialty, number_military_discount_specialty, name_district_military_office, number_special_accounting ]
         Отпуск: [ kind_leave, getting_started, end_work, number_vacation_days, commencement, end_leave, base_release ]
         Дополнительные сведения: [ more_information ]

      edit:
        title: Редактировать
      new:
        title: Новый сотрудник



