generator:
  class: sfDoctrineGenerator
  param:
    model_class:           JobeetJob
    theme:                 admin
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          jobeet_job
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: [last_name]
      list:
         display: [tab_id, =jobeet_category, first_name, last_name, data_id, education]
         title: Сотрудники
      filter:
          display: [tab_id, last_name, first_name, price, status_id, sf_guard_user_id, city_id, category_id]
      form:
        display:
         Начальные сведения: [ sf_guard_user_id, tab_id, number_insurace, pension_sertificate, nature_work, type_work, category_id, status_id, price ]
         Трудовой договор: [ labor_contract, labor_contract_date ]
         Общие сведения: [ last_name, first_name, three_name, type, data_birth, phone, mobile_phone, city_id, citizenship, adress, email, logo ]
         Паспорт: [ Passport ]
         Знание иностранных языков: [ ForeignLanguage ]
         Образование: [ EducationalInstitution ]
         Послевузовое профессиональное образование: [ EducationalInstitutionExtra ]
         Профессия: [ Profession ]         
         Семейное положение: [ Family ] 
         Воинский учет: [ MilitaryRecords ]		 
         Отпуск: [ LeavingTable ]
         Дополнительные сведения: [ more_information ]

      edit:
        title: Редактировать
      new:
        title: Новый сотрудник