generator:
  class: sfDoctrineGenerator
  param:
    model_class:           JobeetJob
    theme:                 admin
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          jobeet_job
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
         display: [tab_id, =jobeet_category, first_name, last_name, data_id, education]
         title: Сотрудники
      filter:
          display: [tab_id, last_name, first_name]
      form:
        display:
         Начальные сведения: [ sf_guard_user_id, tab_id, number_insurace, pension_sertificate, nature_work, type_work, category_id, status_id ]
         Общие сведения: [ last_name, first_name, three_name, type, data_birth, phone, city_id, adress, email, logo ]
         Паспорт: [ passport_number, issuance_passports, date_issue_passport, code_division ]
         Знание иностранных языков: [ name_foreign_language, degree_knowledge_foreign_languages ]
         Образование: [ education_id, name_educational_institution, diploma, year_graduation, diploma_qualification, speciality_diploma ]
         Послевузовое профессиональное образование: [ name_educational_institution_extra, diploma_extra, year_graduation_extra, diploma_qualification_extra, speciality_diploma_extra ]
         Профессия: [ main_profession, other_profession, total_length, continuous_service, last_job, termination_date ]
         Семейное положение: [ marriage_status, children, date_birth_children ]
         Воинский учет: [ group_accounting, category_accounting, composition, military_rank, military_discount_specialty, number_military_discount_specialty, name_district_military_office, number_special_accounting ]
         Отпуск: [ kind_leave, getting_started, end_work, number_vacation_days, commencement, end_leave, base_release ]
         Дополнительные сведения: [ more_information ]

      edit:
        title: Редактировать
      new:
        title: Новый сотрудник



