<?php
// auto-generated by sfDatabaseConfigHandler
<<<<<<< HEAD
// date: 2011/03/30 17:46:19
=======
// date: 2011/03/30 20:32:02
>>>>>>> ec27b1c97778c436fba45a676ab851b3ad70cb2c

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => 666,
  'encoding' => 'utf8',
  'name' => 'doctrine',
)),);
