<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/04/23 09:32:28

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => 666,
  'encoding' => 'utf8',
  'name' => 'doctrine',
)),);
