<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/03/31 14:16:20

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => 666,
  'encoding' => 'utf8',
  'name' => 'doctrine',
)),);
