<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/03/02 18:07:34
$this->security = array (
  'index' => 
  array (
    'is_secure' => true,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
