<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/03/09 17:30:23
sfConfig::add(array(
  'mod_sfguardpermission_enabled' => true,
  'mod_sfguardpermission_view_class' => 'sfPHP',
));
