<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/03/31 19:45:29
$this->security = array (
  'index' => 
  array (
    'credentials' => 
    array (
      0 => 'ADMIN',
    ),
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
