<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/04/22 08:33:24
$this->security = array (
  'index' => 
  array (
    'is_secure' => true,
  ),
  'delete' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'ADMIN',
        1 => 'USER',
      ),
    ),
  ),
  'update' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'ADMIN',
        1 => 'USER',
      ),
    ),
  ),
  'new' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'ADMIN',
        1 => 'USER',
      ),
    ),
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
