generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardPermission
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_permission
    with_doctrine_route:   true

    config:
      list:
        title: Список прав
        display: [=name, description, created_at, updated_at]

      edit:
        title: Редактирование права "%%name%%"

      new:
        title: Новое право

      form:
        display: [name, description, groups_list, users_list]
      filter:
        class: false